CREATE TABLE nsi_auto_model(
    id    INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    model VARCHAR(50) NOT NULL
);

INSERT INTO nsi_auto_model (model) VALUES ('VAZ');
INSERT INTO nsi_auto_model (model) VALUES ('TOYOTA');
INSERT INTO nsi_auto_model (model) VALUES ('BMW');
INSERT INTO nsi_auto_model (model) VALUES ('HONDA');
INSERT INTO nsi_auto_model (model) VALUES ('HONDA');
